// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYTCn1DBmaTJj_qHUTwRGfmyKb0LxwuM',
    appId: '1:723171395893:web:3e35a3026b2709e40b247c',
    messagingSenderId: '723171395893',
    projectId: 'ltdd-a4c6a',
    authDomain: 'ltdd-a4c6a.firebaseapp.com',
    storageBucket: 'ltdd-a4c6a.firebasestorage.app',
    measurementId: 'G-JS6HCC659G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD1P2pKNuFnlhZ8pv_ZzC1vHlCQ6QmfDE',
    appId: '1:723171395893:android:0c3013465974769c0b247c',
    messagingSenderId: '723171395893',
    projectId: 'ltdd-a4c6a',
    storageBucket: 'ltdd-a4c6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxm5xBALJhPpzWK9Cm9v3SEIBgr0elChs',
    appId: '1:723171395893:ios:f4912eccfc79c8da0b247c',
    messagingSenderId: '723171395893',
    projectId: 'ltdd-a4c6a',
    storageBucket: 'ltdd-a4c6a.firebasestorage.app',
    iosBundleId: 'com.example.doanltdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxm5xBALJhPpzWK9Cm9v3SEIBgr0elChs',
    appId: '1:723171395893:ios:f4912eccfc79c8da0b247c',
    messagingSenderId: '723171395893',
    projectId: 'ltdd-a4c6a',
    storageBucket: 'ltdd-a4c6a.firebasestorage.app',
    iosBundleId: 'com.example.doanltdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYTCn1DBmaTJj_qHUTwRGfmyKb0LxwuM',
    appId: '1:723171395893:web:c370e31b0a8b62130b247c',
    messagingSenderId: '723171395893',
    projectId: 'ltdd-a4c6a',
    authDomain: 'ltdd-a4c6a.firebaseapp.com',
    storageBucket: 'ltdd-a4c6a.firebasestorage.app',
    measurementId: 'G-RNYY7F1240',
  );
}
